"use client"
import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
// import '../../node_modules/bootstrap/dist/css/bootstrap.css'
import { Inter } from 'next/font/google'
import { Header } from './Header'
import Footer from './Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
